name: CI

on:
  push:
    branches:
      - "**" # matches every branch
      - "!main" # excludes main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn
      - name: Build and Test
        run: yarn ci
      - run: npm uninstall -g yarn
