name: Publish Node.js Package

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn
      - name: Build and Test
        run: yarn ci
      - run: npm uninstall -g yarn
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm install -g yarn
      - run: yarn
      - name: Build and Test
        run: yarn ci
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm uninstall -g yarn
